local lush = require("lush")
local hsl = lush.hsl

local base = hsl(333, 30, 37)

local RF = 60 -- ROTATION_FACTOR
local DSF = 67 -- DESATURATION_FACTOR
local DKF = 7 -- DARKENING_FACTOR

local red = {
  normal = base,
  bright = base.lighten(DKF * 4),
  soft = base.desaturate(DSF).lighten(DKF),
  dark = base.desaturate(DSF).darken(DKF * 4),
}

local yellow = {
  normal = base.rotate(RF),
  bright = base.rotate(RF).lighten(DKF * 4),
  soft = base.rotate(RF).desaturate(DSF).lighten(DKF),
  dark = base.rotate(RF).desaturate(DSF).darken(DKF * 4),
}

local green = {
  normal = base.rotate(RF * 2),
  bright = base.rotate(RF * 2).lighten(DKF * 4),
  soft = base.rotate(RF * 2).desaturate(DSF).lighten(DKF),
  dark = base.rotate(RF * 2).desaturate(DSF).darken(DKF * 4),

}

local aqua = {
  normal = base.rotate(RF * 3),
  bright = base.rotate(RF * 3).lighten(DKF * 4),
  soft = base.rotate(RF * 3).desaturate(DSF).lighten(DKF),
  dark = base.rotate(RF * 3).desaturate(DSF).darken(DKF * 4),

}

local blue = {
  normal = base.rotate(RF * 4),
  bright = base.rotate(RF * 4).lighten(DKF * 4),
  soft = base.rotate(RF * 4).desaturate(DSF).lighten(DKF),
  dark = base.rotate(RF * 4).desaturate(DSF).darken(DKF * 4),

}

local purple = {
  normal = base.rotate(RF * 5),
  bright = base.rotate(RF * 5).lighten(DKF * 4),
  soft = base.rotate(RF * 5).desaturate(DSF).lighten(DKF),
  dark = base.rotate(RF * 5).desaturate(DSF).darken(DKF * 4),

}

local black = hsl(0, 0, 17)
local white = hsl(0, 0, 83)
local gray = {
  darkestest = black.lighten(DKF * 0.25),
  darkest = black.lighten(DKF * 0.5),
  darker = black.lighten(DKF * 1.5),
  dark = black.lighten(DKF * 2.5),
  normal = hsl(0, 0, 50),
  light = white.darken(DKF * 3),
  lighter = white.darken(DKF * 2),
  lightest = white.darken(DKF),
  lightestest = white.darken(DKF * 0.5),
}

vim.g.terminal_color_0 = gray.darkestest
vim.g.terminal_color_1 = red.soft
vim.g.terminal_color_2 = green.soft
vim.g.terminal_color_3 = yellow.soft
vim.g.terminal_color_4 = blue.soft
vim.g.terminal_color_5 = purple.soft
vim.g.terminal_color_6 = aqua.soft
vim.g.terminal_color_7 = gray.dark
vim.g.terminal_color_8 = gray.light
vim.g.terminal_color_9 = red.normal
vim.g.terminal_color_10 = green.normal
vim.g.terminal_color_11 = yellow.normal
vim.g.terminal_color_12 = blue.normal
vim.g.terminal_color_13 = purple.normal
vim.g.terminal_color_14 = aqua.normal
vim.g.terminal_color_15 = gray.lightestest

---@diagnostic disable: undefined-global
return lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    EndOfBuffer {fg = black},
    NvimTreeEndOfBuffer {EndOfBuffer},
    DapUIEndofBuffer {EndOfBuffer},
    TermCursor {gui = "reverse"},
    NonText {fg = gray.normal},
    SpecialKey {NonText},
    Directory {fg = green.normal},
    NvimTreeSymlinkFolderName {Directory},
    qfFileName {Directory},
    NavicIconsFile {Directory},
    ErrorMsg {fg = red.normal},
    NvimInvalidSpacing {ErrorMsg},
    IncSearch {bg = green.soft, fg = black},
    CurSearch {IncSearch},
    MiniSurround {IncSearch},
    Search {bg = yellow.soft, fg = gray.light},
    AerialLine {Search},
    FocusedSymbol {Search},
    TelescopeMatching {Search},
    MoreMsg {gui = "bold", fg = blue.soft},
    Question {MoreMsg},
    ModeMsg {gui = "bold", fg = yellow.soft},
    LineNr {fg = gray.normal},
    LineNrAbove {LineNr},
    LineNrBelow {LineNr},
    NvimTreeLineNr {LineNr},
    qfLineNr {LineNr},
    FidgetTask {LineNr},
    CursorLineNr {gui = "bold", fg = yellow.soft},
    NvimTreeCursorLineNr {CursorLineNr},
    StatusLine {bg = gray.darker, fg = gray.light},
    MsgSeparator {StatusLine},
    NvimTreeStatusLine {StatusLine},
    MiniStatuslineFilename {StatusLine},
    StatusLineNC {bg = black, fg = gray.normal},
    NvimTreeStatusLineNC {StatusLineNC},
    MiniStatuslineInactive {StatusLineNC},
    VertSplit {fg = black},
    WinSeparator {VertSplit},
    NvimTreeVertSplit {VertSplit},
    Title {gui = "bold", fg = green.normal},
    FloatTitle {Title},
    sym "@text.title" {Title},
    FidgetTitle {Title},
    DashboardHeader {Title},
    LspSagaBorderTitle {Title},
    MiniStarterHeader {Title},
    LspSagaCodeActionTitle {Title},
    Visual {bg = green.soft, fg = gray.lighter},
    VisualNOS {Visual},
    WarningMsg {fg = yellow.soft},
    Folded {bg = gray.darkestest, fg = gray.normal},
    FoldColumn {fg = gray.normal},
    CursorLineFold {FoldColumn},
    DiffAdd {bg = green.dark},
    DiffChange {bg = blue.dark},
    DiffDelete {bg = red.dark},
    DiffText {bg = aqua.dark},
    SignColumn {fg = gray.normal},
    CursorLineSign {SignColumn},
    SignColumnSB {SignColumn},
    Conceal {fg = gray.darker},
    NeoTreeDimText {Conceal},
    SymbolOutlineConnector {Conceal},
    NeotestExpandMarker {Conceal},
    NeotestIndent {Conceal},
    SpellBad {gui = "undercurl", sp = red.soft},
    SpellCap {gui = "undercurl", sp = yellow.soft},
    SpellRare {gui = "undercurl", sp = blue.soft},
    SpellLocal {gui = "undercurl", sp = blue.soft},
    Pmenu {bg = gray.darkestest, fg = gray.light},
    WildMenu {Pmenu},
    PmenuKind {Pmenu},
    PmenuExtra {Pmenu},
    PmenuSbar {Pmenu},
    PmenuSel {bg = yellow.soft},
    PmenuKindSel {PmenuSel},
    PmenuExtraSel {PmenuSel},
    PmenuThumb {bg = yellow.soft},
    TabLine {bg = gray.darkestest, fg = gray.normal},
    TabLineSel {bg = gray.normal, fg = gray.darkestest},
    TabLineFill {bg = black},
    MiniTablineFill {TabLineFill},
    CursorLine {bg = gray.darkest},
    CursorColumn {CursorLine},
    QuickFixLine {CursorLine},
    NvimTreeCursorLine {CursorLine},
    TelescopeSelection {CursorLine},
    ColorColumn {bg = gray.darkestest},
    Whitespace {fg = gray.darkest},
    NormalNC {bg = gray.darkest, fg = gray.normal},
    NormalFloat {bg = gray.darkest, fg = gray.light},
    NvimTreeNormalFloat {NormalFloat},
    DapUIFloatNormal {NormalFloat},
    FloatBorder {fg = gray.normal},
    DapUIFloatBorder {FloatBorder},
    WinBar {gui = "bold", bg = gray.darkestest, fg = gray.normal},
    WinBarNC {gui = "bold", bg = gray.darkestest, fg = gray.normal},
    Cursor {bg = gray.light, fg = gray.darkestest},
    lCursor {Cursor},
    CursorIM {Cursor},
    Normal {bg = gray.darkest, fg = gray.lighter},
    NvimSpacing {Normal},
    NvimTreePopup {Normal},
    DapUINormal {Normal},
    DapUIFrameName {Normal},
    MiniStarterItem {Normal},
    NeotestTest {Normal},
    Substitute {bg = red.soft, fg = gray.darkestest},
    FloatShadow {blend = 80, bg = black},
    FloatShadowThrough {blend = 100, bg = black},
    RedrawDebugNormal {gui = "reverse"},
    RedrawDebugClear {bg = yellow.normal},
    RedrawDebugComposed {bg = green.normal},
    RedrawDebugRecompose {bg = red.normal},
    Error {fg = red.soft},
    NvimInvalid {Error},
    sym "@error" {Error},
    luaParenError {Error},
    luaError {Error},
    Todo {bg = blue.soft, fg = gray.darkestest},
    luaTodo {Todo},
    String {fg = green.soft},
    Character {String},
    sym "@string" {String},
    NvimString {String},
    DapUIThread {String},
    NavicIconsString {String},
    LspSagaCodeActionContent {String},
    DashboardCenter {String},
    luaString2 {String},
    luaString {String},
    Constant {fg = red.soft},
    sym "@constant" {Constant},
    sym "@lsp.type.enumMember" {Constant},
    NavicIconsEvent {Constant},
    sym "@attribute" {Constant},
    NavicIconsEnum {Constant},
    NavicIconsInterface {Constant},
    NavicIconsConstant {Constant},
    CmpItemKindEnum {Constant},
    CmpItemKindEvent {Constant},
    CmpItemKindUnit {Constant},
    CmpItemKindInterface {Constant},
    luaConstant {Constant},
    Number {fg = aqua.soft},
    Boolean {Number},
    Float {Number},
    sym "@number" {Number},
    sym "@float" {Number},
    NvimNumber {Number},
    DapUILineNumber {Number},
    NavicIconsNumber {Number},
    luaNumber {Number},
    Function {fg = green.normal},
    sym "@function" {Function},
    sym "@lsp.type.decorator" {Function},
    sym "@lsp.type.function" {Function},
    sym "@lsp.type.method" {Function},
    WhichKeyGroup {Function},
    CmpItemKindConstructor {Function},
    NavicIconsConstructor {Function},
    NavicIconsFunction {Function},
    CmpItemKindFunction {Function},
    CmpItemKindMethod {Function},
    NavicIconsMethod {Function},
    luaMetaMethod {Function},
    luaFunction {Function},
    Identifier {fg = gray.light},
    NvimIdentifier {Identifier},
    NavicIconsKey {Identifier},
    DashboardShortCut {Identifier},
    CmpItemKindKeyword {Identifier},
    WhichKey {Identifier},
    luaFunc {Identifier},
    Conditional {fg = red.normal},
    Repeat {Conditional},
    Label {Conditional},
    sym "@conditional" {Conditional},
    luaCondElse {Conditional},
    luaCond {Conditional},
    Statement {fg = blue.soft},
    luaStatement {Statement},
    Operator {fg = gray.normal},
    sym "@operator" {Operator},
    NvimAssignment {Operator},
    NvimOperator {Operator},
    NagicIconsOperator {Operator},
    CmpItemKindOperator {Operator},
    luaOperator {Operator},
    Keyword {fg = blue.soft},
    Exception {Keyword},
    sym "@keyword" {Keyword},
    DapUISource {Keyword},
    WhichKeyDesc {Keyword},
    CmpItemKindReference {Keyword},
    CmpItemKindValue {Keyword},
    PreProc {fg = gray.normal},
    Include {PreProc},
    Define {PreProc},
    Macro {PreProc},
    PreCondit {PreProc},
    sym "@preproc" {PreProc},
    Type {fg = aqua.normal},
    StorageClass {Type},
    Structure {Type},
    Typedef {Type},
    sym "@type" {Type},
    sym "@lsp.type.type" {Type},
    NvimNumberPrefix {Type},
    NvimOptionSigil {Type},
    DapUIType {Type},
    NavicIconsStruct {Type},
    NavicIconsNull {Type},
    NavicIconsClass {Type},
    CmpItemKindStruct {Type},
    CmpItemKindClass {Type},
    Special {fg = green.normal},
    Tag {Special},
    SpecialChar {Special},
    Delimiter {Special},
    SpecialComment {Special},
    Debug {Special},
    sym "@string.special" {Special},
    DiagnosticError {fg = red.soft},
    DiagnosticFloatingError {DiagnosticError},
    DiagnosticSignError {DiagnosticError},
    NvimTreeLspDiagnosticsError {DiagnosticError},
    DiagnosticWarn {fg = yellow.soft},
    DiagnosticFloatingWarn {DiagnosticWarn},
    DiagnosticSignWarn {DiagnosticWarn},
    NvimTreeLspDiagnosticsWarning {DiagnosticWarn},
    DiagnosticInfo {fg = blue.soft},
    DiagnosticFloatingInfo {DiagnosticInfo},
    DiagnosticSignInfo {DiagnosticInfo},
    NvimTreeLspDiagnosticsInformation {DiagnosticInfo},
    DiagnosticHint {fg = green.soft},
    DiagnosticFloatingHint {DiagnosticHint},
    DiagnosticSignHint {DiagnosticHint},
    NvimTreeLspDiagnosticsHint {DiagnosticHint},
    DiagnosticOk {fg = green.normal},
    DiagnosticVirtualTextOk {DiagnosticOk},
    DiagnosticFloatingOk {DiagnosticOk},
    DiagnosticSignOk {DiagnosticOk},
    DiagnosticUnderlineError {gui = "undercurl", sp = red.soft},
    DiagnosticUnderlineWarn {gui = "undercurl", sp = yellow.soft},
    DiagnosticUnderlineInfo {gui = "undercurl", sp = blue.soft},
    DiagnosticUnderlineHint {gui = "undercurl", sp = green.soft},
    DiagnosticUnderlineOk {gui = "underline", sp = green.normal},
    DiagnosticVirtualTextError {bg = red.dark, fg = red.soft},
    DiagnosticVirtualTextWarn {bg = yellow.dark, fg = yellow.soft},
    DiagnosticVirtualTextInfo {bg = blue.dark, fg = blue.soft},
    DiagnosticVirtualTextHint {bg = green.dark, fg = green.soft},
    DiagnosticDeprecated {gui = "strikethrough", sp = red.soft},
    Comment {fg = gray.darker},
    DiagnosticUnnecessary {Comment},
    sym "@comment" {Comment},
    sym "@lsp.type.comment" {Comment},
    NvimTreeGitIgnored {Comment},
    CmpItemMenu {Comment},
    WhichKeyValue {Comment},
    WhichKeySeperator {Comment},
    WhichKeySeparator {Comment},
    MiniStarterInactive {Comment},
    luaComment {Comment},
    sym "@text" {fg = gray.light},
    sym "@text.literal" {gui = "italic", fg = yellow.soft},
    sym "@text.reference" {gui = "bold", fg = blue.soft},
    sym "@text.uri" {gui = "underline,italic", fg = red.soft},
    Underlined {gui = "underline"},
    sym "@text.todo" {bg = green.soft, fg = gray.darkestest},
    sym "@constant.builtin" {fg = purple.soft},
    sym "@string.escape" {gui = "bold", fg = yellow.normal},
    sym "@function.builtin" {fg = gray.light},
    sym "@lsp.typemod.function.defaultLibrary" {sym "@function.builtin"},
    sym "@lsp.typemod.method.defaultLibrary" {sym "@function.builtin"},
    sym "@function.macro" {fg = gray.light},
    sym "@parameter" {fg = gray.normal},
    sym "@lsp.type.parameter" {sym "@parameter"},
    sym "@field" {fg = red.soft},
    sym "@property" {sym "@field"},
    NavicIconsEnumMember {sym "@field"},
    NavicIconsField {sym "@field"},
    NavicIconsTypeParameter {sym "@field"},
    sym "@constructor" {fg = yellow.soft},
    sym "@exception" {fg = gray.light},
    sym "@variable" {fg = gray.lightest},
    NavicIconsVariable {sym "@variable"},
    sym "@namespace" {fg = gray.normal},
    sym "@lsp.type.namespace" {sym "@namespace"},
    NavicIconsNamespace {sym "@namespace"},
    NavicIconsPackage {sym "@namespace"},
    NavicIconsModule {sym "@namespace"},
    NavicIconsObject {sym "@namespace"},
    sym "@tag" {fg = blue.soft},
    MatchParen {gui = "bold", fg = yellow.soft},
    Ignore {fg = black},
    NvimInternalError {bg = red.bright, fg = white},
    NvimFigureBrace {NvimInternalError},
    NvimSingleQuotedUnknownEscape {NvimInternalError},
    NvimInvalidSingleQuotedUnknownEscape {NvimInternalError},
    NvimTreeLiveFilterValue {gui = "bold"},
    NvimTreeBookmark {fg = red.dark},
    NvimTreeIndentMarker {fg = gray.darker},
    NvimTreeSymlink {fg = purple.normal},
    NvimTreeFolderIcon {fg = blue.soft},
    NvimTreeOpenedFolderIcon {NvimTreeFolderIcon},
    NvimTreeClosedFolderIcon {NvimTreeFolderIcon},
    NvimTreeRootFolder {gui = "bold", fg = red.soft},
    NvimTreeExecFile {gui = "bold", fg = red.dark},
    NvimTreeSpecialFile {fg = aqua.soft},
    NvimTreeImageFile {fg = gray.lightest},
    NvimTreeOpenedFile {fg = purple.soft},
    NvimTreeModifiedFile {fg = red.dark},
    NvimTreeGitDirty {fg = yellow.soft},
    NvimTreeFileDirty {NvimTreeGitDirty},
    NvimTreeGitDeleted {fg = red.normal},
    NvimTreeGitRenamed {NvimTreeGitDeleted},
    NvimTreeFileDeleted {NvimTreeGitDeleted},
    NvimTreeGitMerge {fg = red.soft},
    NvimTreeFileMerge {NvimTreeGitMerge},
    NvimTreeGitNew {fg = green.soft},
    NvimTreeFileNew {NvimTreeGitNew},
    NvimTreeWindowPicker {gui = "bold", bg = blue.bright, fg = white},
    NvimTreeLiveFilterPrefix {gui = "bold", fg = purple.normal},
    NvimTreeNormal {bg = black, fg = gray.light},
    NvimTreeSignColumn {NvimTreeNormal},
    NvimTreeNormalNC {NvimTreeNormal},
    NvimTreeFolderName {fg = blue.soft},
    NvimTreeEmptyFolderName {fg = gray.normal},
    NvimTreeOpenedFolderName {fg = blue.dark},
    DevIconJson {fg = "#cbcb41"},
    DevIconVim {fg = "#019833"},
    DevIconLua {fg = "#51a0cf"},
    DevIconQuery {fg = "#90a850"},
    DevIconRake {fg = "#701516"},
    DevIconD {fg = "#427819"},
    DevIconReScript {fg = "#cc3e44"},
    DevIconReScriptInterface {fg = "#f55385"},
    DevIconFs {fg = "#519aba"},
    DevIconRlib {fg = "#dea584"},
    DevIconRproj {fg = "#358a5b"},
    DevIconRs {fg = "#dea584"},
    DevIconRss {fg = "#fb9d3b"},
    DevIconSass {fg = "#f55385"},
    DevIconsbt {fg = "#cc3e44"},
    DevIconScala {fg = "#cc3e44"},
    DevIconTor {fg = "#519aba"},
    DevIconScheme {fg = "#000000"},
    DevIconScss {fg = "#f55385"},
    DevIconC {fg = "#599eff"},
    DevIconSh {fg = "#4d5a5e"},
    DevIconSig {fg = "#e37933"},
    DevIconSlim {fg = "#e34c26"},
    DevIconSln {fg = "#854cc7"},
    DevIconSml {fg = "#e37933"},
    DevIconSql {fg = "#dad8d8"},
    DevIconStyl {fg = "#8dc149"},
    DevIconSuo {fg = "#e37933"},
    DevIconSystemVerilog {fg = "#019833"},
    DevIconSvelte {fg = "#ff3e00"},
    DevIconSvg {fg = "#ffb13b"},
    DevIconSwift {fg = "#e37933"},
    DevIconTcl {fg = "#1e5cb3"},
    DevIconTex {fg = "#3d6117"},
    DevIconTerraform {fg = "#5f43e9"},
    DevIconTFVars {fg = "#5f43e9"},
    DevIconToml {fg = "#6d8086"},
    DevIconTextResource {fg = "#cbcb41"},
    DevIconTestTs {fg = "#519aba"},
    DevIconMli {fg = "#e37933"},
    DevIconSpecTs {fg = "#519aba"},
    DevIconMotoko {fg = "#9772fb"},
    DevIconTextScene {fg = "#a074c4"},
    DevIconTsx {fg = "#1354bf"},
    DevIconMustache {fg = "#e37933"},
    DevIconNim {fg = "#f3d400"},
    DevIconTypeScriptReactTest {fg = "#1354bf"},
    DevIconTypeScriptReactSpec {fg = "#1354bf"},
    DevIconNix {fg = "#7ebae4"},
    DevIconOPUS {fg = "#f88a02"},
    DevIconOrgMode {fg = "#77aa99"},
    DevIconOpenTypeFont {fg = "#ececec"},
    DevIconPackedResource {fg = "#6d8086"},
    DevIconTxt {fg = "#89e051"},
    DevIconPdf {fg = "#b30b00"},
    DevIconVala {fg = "#7239b3"},
    DevIconPhp {fg = "#a074c4"},
    DevIconVerilog {fg = "#019833"},
    DevIconPl {fg = "#519aba"},
    DevIconVHDL {fg = "#019833"},
    DevIconPm {fg = "#519aba"},
    DevIconVue {fg = "#8dc149"},
    DevIconPp {fg = "#ffa61a"},
    DevIconWebmanifest {fg = "#f1e05a"},
    DevIconPpt {fg = "#cb4a32"},
    DevIconWebp {fg = "#a074c4"},
    DevIconR {fg = "#358a5b"},
    DevIconXcPlayground {fg = "#e37933"},
    DevIconProlog {fg = "#e4b854"},
    DevIconXls {fg = "#207245"},
    DevIconXlsx {fg = "#207245"},
    DevIconXml {fg = "#e37933"},
    DevIconPsManifestfile {fg = "#6975c4"},
    DevIconXul {fg = "#e37933"},
    DevIconPsScriptModulefile {fg = "#6975c4"},
    DevIconYaml {fg = "#6d8086"},
    DevIconPsb {fg = "#519aba"},
    DevIconYml {fg = "#6d8086"},
    DevIconZig {fg = "#f69a1b"},
    DevIconPy {fg = "#ffbc03"},
    DevIconZsh {fg = "#89e051"},
    DevIconPyc {fg = "#ffe291"},
    DevIconSolidity {fg = "#519aba"},
    DevIconPrisma {fg = "#ffffff"},
    DevIconPyo {fg = "#ffe291"},
    DevIconLock {fg = "#bbbbbb"},
    DevIconWasm {fg = "#5c4cdb"},
    DevIconLiquid {fg = "#95bf47"},
    DevIconTerminal {fg = "#31b53e"},
    DevIconDefault {fg = "#6d8086"},
    DevIconEex {fg = "#a074c4"},
    DevIconEjs {fg = "#cbcb41"},
    DevIconElm {fg = "#519aba"},
    DevIconEpp {fg = "#ffa61a"},
    DevIconDump {fg = "#dad8d8"},
    DevIconErb {fg = "#701516"},
    DevIconErl {fg = "#b83998"},
    DevIconEx {fg = "#a074c4"},
    DevIconExs {fg = "#a074c4"},
    DevIconFsharp {fg = "#519aba"},
    DevIconFortran {fg = "#734f96"},
    DevIconFennel {fg = "#fff3d7"},
    DevIconLog {fg = "#ffffff"},
    DevIconFish {fg = "#4d5a5e"},
    DevIconFsi {fg = "#519aba"},
    DevIconFsscript {fg = "#519aba"},
    DevIconFsx {fg = "#519aba"},
    DevIconGDScript {fg = "#6d8086"},
    DevIconGemspec {fg = "#701516"},
    DevIconBinaryGLTF {fg = "#ffb13b"},
    DevIconGodotProject {fg = "#6d8086"},
    DevIconGraphQL {fg = "#e535ab"},
    DevIconH {fg = "#a074c4"},
    DevIconHaml {fg = "#eaeae1"},
    DevIconHbs {fg = "#f0772b"},
    DevIconHeex {fg = "#a074c4"},
    DevIconHh {fg = "#a074c4"},
    DevIconVagrantfile {fg = "#1563ff"},
    DevIconHrl {fg = "#b83998"},
    DevIconHs {fg = "#a074c4"},
    DevIconDockerfile {fg = "#458ee6"},
    DevIconVimrc {fg = "#019833"},
    DevIconHtm {fg = "#e34c26"},
    DevIconBazelWorkspace {fg = "#89e051"},
    DevIconGitLogo {fg = "#f14c28"},
    DevIconHtml {fg = "#e44d26"},
    DevIconAi {fg = "#cbcb41"},
    DevIconNodeModules {fg = "#e8274b"},
    DevIconHxx {fg = "#a074c4"},
    DevIconAwk {fg = "#4d5a5e"},
    DevIconIco {fg = "#cbcb41"},
    DevIconImportConfiguration {fg = "#ececec"},
    DevIconMakefile {fg = "#6d8086"},
    DevIconBash {fg = "#89e051"},
    DevIconBat {fg = "#c1f12e"},
    DevIconJava {fg = "#cc3e44"},
    DevIconBazel {fg = "#89e051"},
    DevIconEnv {fg = "#faf743"},
    DevIconBzl {fg = "#89e051"},
    DevIconBmp {fg = "#a074c4"},
    DevIconGruntfile {fg = "#e37933"},
    DevIconJs {fg = "#cbcb41"},
    DevIconTestJs {fg = "#cbcb41"},
    DevIconCPlusPlus {fg = "#f34b7d"},
    DevIconGulpfile {fg = "#cc3e44"},
    DevIconSpecJs {fg = "#cbcb41"},
    DevIconCobol {fg = "#005ca5"},
    DevIconWebpack {fg = "#519aba"},
    DevIconJsx {fg = "#20c2e3"},
    DevIconRakefile {fg = "#701516"},
    DevIconConfiguration {fg = "#ececec"},
    DevIconJavaScriptReactTest {fg = "#20c2e3"},
    DevIconJavaScriptReactSpec {fg = "#20c2e3"},
    DevIconKsh {fg = "#4d5a5e"},
    DevIconKotlin {fg = "#7f52ff"},
    DevIconClojure {fg = "#8dc149"},
    DevIconJpg {fg = "#a074c4"},
    DevIconRmd {fg = "#519aba"},
    DevIconRb {fg = "#701516"},
    DevIconKotlinScript {fg = "#7f52ff"},
    DevIconMl {fg = "#e37933"},
    DevIconClojureJS {fg = "#519aba"},
    DevIconJpeg {fg = "#a074c4"},
    DevIconLess {fg = "#563d7c"},
    DevIconGif {fg = "#a074c4"},
    DevIconCjs {fg = "#cbcb41"},
    DevIconCMake {fg = "#6d8086"},
    DevIconGvimrc {fg = "#019833"},
    DevIconBashrc {fg = "#89e051"},
    DevIconBabelrc {fg = "#cbcb41"},
    DevIconDsStore {fg = "#41535b"},
    DevIconMarkdown {fg = "#519aba"},
    DevIconConfigRu {fg = "#701516"},
    DevIconMaterial {fg = "#b83998"},
    DevIconEslintrc {fg = "#4b32c3"},
    DevIconMd {fg = "#ffffff"},
    DevIconBazelBuild {fg = "#89e051"},
    DevIconGitAttributes {fg = "#41535b"},
    DevIconMdx {fg = "#519aba"},
    DevIconGitConfig {fg = "#41535b"},
    DevIconMint {fg = "#87c095"},
    DevIconGitIgnore {fg = "#41535b"},
    DevIconLicense {fg = "#d0bf41"},
    DevIconGitlabCI {fg = "#e24329"},
    DevIconCp {fg = "#519aba"},
    DevIconMjs {fg = "#f1e05a"},
    DevIconCsh {fg = "#4d5a5e"},
    DevIconJl {fg = "#a270ba"},
    DevIconCson {fg = "#cbcb41"},
    DevIconCs {fg = "#596706"},
    DevIconCss {fg = "#42a5f5"},
    DevIconTwig {fg = "#8dc149"},
    DevIconLhs {fg = "#a074c4"},
    DevIconClojureC {fg = "#8dc149"},
    DevIconNPMIgnore {fg = "#e8274b"},
    DevIconProcfile {fg = "#a074c4"},
    DevIconCrystal {fg = "#c8c8c8"},
    DevIconCxx {fg = "#519aba"},
    DevIconDesktopEntry {fg = "#563d7c"},
    DevIconNPMrc {fg = "#e8274b"},
    DevIconPyd {fg = "#ffe291"},
    DevIconSettingsJson {fg = "#854cc7"},
    DevIconPsd {fg = "#519aba"},
    DevIconPng {fg = "#a074c4"},
    DevIconGitModules {fg = "#41535b"},
    DevIconDb {fg = "#dad8d8"},
    DevIconZshprofile {fg = "#89e051"},
    DevIconCoffee {fg = "#cbcb41"},
    DevIconZshenv {fg = "#89e051"},
    DevIconLuau {fg = "#51a0cf"},
    DevIconZshrc {fg = "#89e051"},
    DevIconPsScriptfile {fg = "#4273ca"},
    DevIconBrewfile {fg = "#701516"},
    DevIconDoc {fg = "#185abd"},
    DevIconClojureDart {fg = "#519aba"},
    DevIconCMakeLists {fg = "#6d8086"},
    DevIconLeex {fg = "#a074c4"},
    DevIconCpp {fg = "#519aba"},
    DevIconDocx {fg = "#185abd"},
    DevIconGitCommit {fg = "#41535b"},
    DevIconDrools {fg = "#ffafaf"},
    DevIconJson5 {fg = "#cbcb41"},
    DevIconMixLock {fg = "#a074c4"},
    DevIconIni {fg = "#6d8086"},
    DevIconDropbox {fg = "#0061fe"},
    DevIconFavicon {fg = "#cbcb41"},
    DevIconHpp {fg = "#a074c4"},
    DevIconEdn {fg = "#519aba"},
    DevIconDiff {fg = "#41535b"},
    DevIconConf {fg = "#6d8086"},
    DevIconGemfile {fg = "#701516"},
    DevIconPackageJson {fg = "#e8274b"},
    DevIconPackageLockJson {fg = "#7a0d21"},
    DevIconCsv {fg = "#89e051"},
    DevIconTs {fg = "#519aba"},
    DevIconDart {fg = "#03589c"},
    DevIconBashProfile {fg = "#89e051"},
    DevIconGo {fg = "#519aba"},
    TreesitterContext {bg = gray.darkestest},
    TreesitterContextLineNumber {},
    TreesitterContextBottom {},
    TreesitterContextSeparator {},
    NullLsInfoTitle {gui = "bold"},
    NullLsInfoBorder {},
    NullLsInfoHeader {fg = aqua.soft},
    NullLsInfoSources {fg = yellow.soft},
    DapUIVariable {Identifier},
    DapUIScope {fg = aqua.normal},
    DapUIValue {Identifier},
    DapUIModifiedValue {Identifier, gui = "bold"},
    DapUIDecoration {fg = gray.normal},
    DapUIStoppedThread {fg = aqua.normal},
    DapUIWatchesEmpty {fg = red.soft},
    DapUIWatchesValue {fg = yellow.soft},
    DapUIWatchesError {fg = red.soft},
    DapUIBreakpointsPath {fg = aqua.normal},
    DapUIBreakpointsInfo {fg = blue.soft},
    DapUIBreakpointsCurrentLine {gui = "bold", fg = green.soft},
    DapUICurrentFrameName {DapUIBreakpointsCurrentLine},
    DapUIBreakpointsDisabledLine {fg = gray.darker},
    DapUIStepOver {fg = blue.bright},
    DapUIStepInto {fg = blue.bright},
    DapUIStepBack {fg = blue.bright},
    DapUIStepOut {fg = blue.bright},
    DapUIStop {fg = red.bright},
    DapUIPlayPause {fg = green.bright},
    DapUIRestart {fg = green.bright},
    DapUIUnavailable {fg = gray.darker},
    DapUIWinSelect {gui = "bold", fg = blue.bright},
    DapUINormalNC {},
    DapUIPlayPauseNC {fg = green.bright},
    DapUIRestartNC {fg = green.bright},
    DapUIStopNC {fg = red.bright},
    DapUIUnavailableNC {fg = gray.darker},
    DapUIStepOverNC {fg = blue.bright},
    DapUIStepIntoNC {fg = blue.bright},
    DapUIStepBackNC {fg = blue.bright},
    DapUIStepOutNC {fg = blue.bright},
    CmpItemAbbrMatch {fg = green.normal},
    LspCodeLens {fg = gray.darker},
    LspCodeLensSeparator {fg = gray.normal},
    LspSignatureActiveParameter {fg = yellow.soft},
    sym "@type.builtin" {fg = gray.normal},
    sym "@variable.builtin" {fg = gray.light},
    sym "@lsp.typemod.variable.defaultLibrary" {sym "@variable.builtin"},
    AerialGuide {fg = gray.darker},
    BufferCurrent {bg = gray.normal, fg = gray.light},
    BufferCurrentIndex {bg = gray.normal, fg = blue.soft},
    BufferCurrentMod {bg = gray.normal, fg = yellow.soft},
    BufferCurrentSign {bg = gray.normal, fg = blue.soft},
    BufferCurrentTarget {bg = gray.normal, fg = red.soft},
    BufferInactive {bg = black, fg = gray.darker},
    BufferInactiveIndex {bg = black, fg = gray.darker},
    BufferInactiveMod {bg = black, fg = yellow.dark},
    CmpItemAbbrDeprecated {gui = "strikethrough", fg = gray.normal},
    BufferInactiveSign {bg = black, fg = gray.darkest},
    BufferTabpages {bg = black},
    BufferVisibleIndex {bg = black, fg = blue.soft},
    MiniTestPass {gui = "bold", fg = green.soft},
    NeogitRemote {fg = green.soft},
    MiniTestEmphasis {gui = "bold"},
    MiniTablineVisible {bg = gray.darkestest, fg = gray.normal},
    SignifySignDelete {fg = red.soft},
    MiniTablineModifiedCurrent {
      gui = "bold",
      bg = gray.normal,
      fg = gray.darker,
    },
    MiniStatuslineModeReplace {gui = "bold", bg = red.soft, fg = black},
    MiniStatuslineModeOther {gui = "bold", bg = blue.soft, fg = black},
    sym "@punctuation.delimiter" {fg = yellow.soft},
    sym "@keyword.operator" {fg = gray.normal},
    TSRainbowBlue {fg = blue.soft},
    sym "@field.rust" {fg = gray.normal},
    PounceGap {bg = gray.darkestest, fg = gray.light},
    NotifyTRACEBorder {fg = gray.darker},
    NeotestMarked {gui = "bold", fg = gray.light},
    sym "@text.environment" {fg = gray.normal},
    sym "@text.environment.name" {fg = green.normal},
    diffLine {fg = purple.soft},
    diffIndexLine {fg = gray.normal},
    diffFile {fg = blue.soft},
    diffChanged {fg = yellow.soft},
    WhichKeyFloat {bg = black},
    LspReferenceText {bg = gray.darkestest},
    illuminatedWordWrite {LspReferenceText},
    illuminatedWordRead {LspReferenceText},
    illuminatedWordText {LspReferenceText},
    MiniCursorword {LspReferenceText},
    MiniCursorwordCurrent {LspReferenceText},
    GlyphPalette5 {fg = purple.soft},
    GlyphPalette4 {fg = blue.soft},
    GlyphPalette14 {fg = aqua.normal},
    GlyphPalette10 {fg = green.normal},
    GlyphPalette0 {fg = black},
    NotifyINFOTitle {fg = blue.soft},
    NotifyINFOIcon {NotifyINFOTitle},
    TSRainbowViolet {fg = purple.soft},
    GlyphPalette11 {fg = yellow.normal},
    BufferTabpage {bg = black, fg = gray.darkest},
    BufferVisible {bg = black, fg = gray.light},
    NeoTreeDirectoryIcon {fg = blue.soft},
    ModesVisual {bg = purple.soft},
    NeotestPassed {fg = green.soft},
    ModesDelete {bg = red.soft},
    NeotestFile {fg = blue.soft},
    NeotestFocused {gui = "underline"},
    MiniTrailspace {bg = red.soft},
    sym "@text.math" {fg = green.normal},
    PounceAcceptBest {bg = aqua.normal, fg = gray.darkestest},
    PounceMatch {bg = yellow.soft, fg = gray.light},
    diffAdded {fg = green.soft},
    sym "@text.diff.add" {diffAdded},
    GitGutterChange {fg = yellow.soft},
    GitGutterDelete {fg = red.soft},
    GlyphPalette1 {fg = red.soft},
    Sneak {bg = purple.soft, fg = black},
    SneakScope {bg = gray.darkestest},
    GlyphPalette12 {fg = blue.dark},
    GlyphPalette13 {fg = purple.soft},
    GlyphPalette15 {fg = gray.lightest},
    GlyphPalette2 {fg = green.soft},
    GlyphPalette3 {fg = yellow.soft},
    GlyphPalette6 {fg = aqua.soft},
    rainbowcol1 {fg = red.soft},
    rainbowcol2 {fg = yellow.soft},
    rainbowcol3 {fg = green.soft},
    rainbowcol4 {fg = blue.soft},
    rainbowcol5 {fg = aqua.soft},
    rainbowcol6 {fg = purple.soft},
    rainbowcol7 {fg = purple.soft},
    diffNewFile {fg = green.soft},
    diffOldFile {fg = yellow.soft},
    diffRemoved {fg = red.soft},
    sym "@text.diff.delete" {diffRemoved},
    NeotestRunning {fg = red.soft},
    NeotestNamespace {fg = blue.bright},
    sym "@keyword.function" {fg = blue.soft},
    TSRainbowCyan {fg = aqua.soft},
    TSRainbowGreen {fg = green.soft},
    TSRainbowOrange {fg = red.soft},
    TSRainbowRed {fg = red.soft},
    NavicText {fg = gray.light},
    NavicSeparator {fg = gray.darker},
    sym "@string.regex" {fg = yellow.normal},
    sym "@tag.attribute" {gui = "italic", fg = green.normal},
    sym "@tag.delimiter" {fg = gray.normal},
    MiniStatuslineModeNormal {gui = "bold", bg = aqua.soft, fg = black},
    CmpDocumentation {bg = black, fg = gray.light},
    MiniStatuslineModeVisual {gui = "bold", bg = purple.soft, fg = black},
    NeogitBranch {fg = yellow.soft},
    MiniTablineCurrent {gui = "bold", bg = gray.darker, fg = gray.normal},
    MiniTablineHidden {bg = gray.darkestest, fg = gray.normal},
    NeogitDiffDelete {fg = red.soft},
    NeogitDiffDeleteHighlight {bg = red.dark},
    MiniTablineModifiedVisible {bg = gray.normal, fg = gray.darkestest},
    sym "@field.yaml" {fg = green.normal},
    MiniTestFail {gui = "bold", fg = red.soft},
    sym "@text.danger" {bg = red.soft, fg = gray.darkestest},
    sym "@symbol" {fg = gray.normal},
    TSRainbowYellow {fg = yellow.soft},
    NeoTreeFileName {fg = gray.normal},
    NeoTreeFileNameOpened {fg = gray.light},
    NotifyWARNBorder {fg = yellow.dark},
    BufferVisibleMod {bg = black, fg = yellow.soft},
    NeoTreeNormal {bg = black, fg = gray.light},
    NeoTreeNormalNC {NeoTreeNormal},
    sym "@text.strong" {gui = "bold", fg = red.soft},
    sym "@text.todo.checked" {fg = green.soft},
    sym "@text.emphasis" {gui = "italic", fg = red.soft},
    sym "@text.strike" {gui = "strikethrough", fg = gray.light},
    GitSignsAdd {fg = green.soft},
    SignifySignAdd {fg = green.soft},
    NotifyINFOBorder {fg = blue.dark},
    SignifySignChange {fg = yellow.soft},
    GitSignsDelete {fg = red.soft},
    GlyphPalette7 {fg = gray.lightest},
    GlyphPalette8 {fg = purple.dark},
    GlyphPalette9 {fg = red.normal},
    HopNextKey {gui = "bold", fg = aqua.soft},
    HopNextKey1 {gui = "bold", fg = blue.soft},
    Italic {gui = "italic"},
    LspInlayHint {bg = gray.darkestest, fg = gray.darker},
    LspSagaCodeActionBorder {fg = gray.normal},
    LspSagaDefPreviewBorder {fg = gray.normal},
    LspSagaRenameBorder {fg = gray.normal},
    LspSagaSignatureHelpBorder {fg = red.soft},
    LspTroubleCount {bg = gray.normal, fg = purple.soft},
    LspTroubleNormal {bg = black, fg = gray.normal},
    LspTroubleText {fg = gray.normal},
    MiniCompletionActiveParameter {gui = "underline"},
    sym "@constructor.lua" {fg = gray.normal},
    MiniJump {bg = purple.soft, fg = black},
    MiniJump2dSpot {gui = "bold", fg = aqua.soft},
    MiniStarterCurrent {gui = "nocombine"},
    MiniStarterFooter {gui = "italic", fg = red.soft},
    MiniStarterItemBullet {fg = gray.normal},
    MiniStarterItemPrefix {fg = purple.soft},
    MiniStarterQuery {fg = green.soft},
    MiniStarterSection {fg = red.soft},
    MiniStatuslineModeCommand {gui = "bold", bg = yellow.soft, fg = black},
    MiniStatuslineModeInsert {gui = "bold", bg = green.soft, fg = black},
    CmpItemKindSnippet {fg = gray.normal},
    LspReferenceRead {bg = gray.darkestest},
    LspReferenceWrite {bg = gray.darkestest},
    sym "@punctuation.bracket" {fg = yellow.soft},
    CmpItemKindDefault {fg = green.normal},
    FernBranchText {fg = blue.soft},
    NeogitNotificationError {fg = red.soft},
    NeogitHunkHeaderHighlight {bg = gray.darkestest, fg = blue.soft},
    sym "@text.todo.unchecked" {fg = gray.normal},
    BufferInactiveTarget {bg = black, fg = red.soft},
    MiniStatuslineFileinfo {bg = gray.darkestest, fg = gray.normal},
    MiniStatuslineDevinfo {bg = gray.darkestest, fg = gray.normal},
    MiniIndentscopePrefix {gui = "nocombine"},
    NeoTreeSymbolicLinkTarget {fg = purple.normal},
    NeoTreeRootName {gui = "bold", fg = red.soft},
    PounceAccept {bg = red.normal, fg = gray.darkestest},
    NeoTreeIndentMarker {fg = gray.darker},
    NeoTreeGitModified {fg = yellow.soft},
    NeoTreeGitIgnored {fg = blue.soft},
    NeoTreeGitDeleted {fg = red.soft},
    NeoTreeGitConflict {gui = "italic", fg = red.soft},
    NeoTreeGitAdded {fg = green.soft},
    LspFloatWinNormal {bg = gray.darkestest},
    NeotestDir {fg = aqua.soft},
    NeotestAdapterName {gui = "bold", fg = purple.soft},
    NeoTreeDirectoryName {fg = blue.soft},
    TelescopeBorder {fg = gray.darker},
    TelescopeSelectionCaret {fg = green.soft},
    CmpItemAbbrMatchFuzzy {fg = green.normal},
    GitSignsChange {fg = yellow.soft},
    NotifyWARNTitle {fg = yellow.soft},
    NotifyWARNIcon {NotifyWARNTitle},
    MiniTablineTabpagesection {
      gui = "bold",
      bg = gray.darkestest,
      fg = gray.light,
    },
    NotifyTRACETitle {fg = gray.darker},
    NotifyTRACEIcon {NotifyTRACETitle},
    DashboardFooter {gui = "italic", fg = red.soft},
    NotifyERRORTitle {fg = red.soft},
    NotifyERRORIcon {NotifyERRORTitle},
    NeoTreeGitUntracked {fg = purple.normal},
    NotifyERRORBorder {fg = red.dark},
    NotifyDEBUGTitle {fg = green.soft},
    NotifyDEBUGIcon {NotifyDEBUGTitle},
    NeotestSkipped {fg = yellow.soft},
    CmpDocumentationBorder {bg = black, fg = gray.darkestest},
    Bold {gui = "bold"},
    NotifyDEBUGBorder {fg = green.dark},
    NeoTreeDotfile {fg = blue.normal},
    NeotestFailed {fg = red.soft},
    ModesInsert {bg = aqua.soft},
    ModesCopy {bg = yellow.soft},
    sym "@text.note" {bg = blue.soft, fg = gray.darkestest},
    NeogitNotificationWarning {fg = yellow.soft},
    NeogitNotificationInfo {fg = blue.soft},
    NeogitHunkHeader {bg = gray.darkest, fg = blue.soft},
    MiniTablineModifiedHidden {bg = gray.normal, fg = gray.darkestest},
    NeogitDiffContextHighlight {bg = gray.darker},
    NeogitDiffAddHighlight {bg = green.dark},
    NeogitDiffAdd {fg = green.soft},
    BufferVisibleSign {bg = black, fg = blue.soft},
    LspFloatWinBorder {fg = gray.normal},
    CocInlayHint {bg = gray.darkestest, fg = gray.darker},
    BufferVisibleTarget {bg = black, fg = red.soft},
    sym "@text.warning" {bg = yellow.soft, fg = gray.darkestest},
    sym "@keyword.return" {fg = gray.light},
    sym "@punctuation.special" {fg = gray.normal},
    CmpItemAbbr {fg = gray.light},
    HopUnmatched {fg = gray.darker},
    LightspeedGreyWash {fg = gray.darker},
    LspSagaHoverBorder {fg = gray.normal},
    LspSagaFinderSelection {fg = gray.darkestest},
    GitGutterAdd {fg = green.soft},
    HopNextKey2 {fg = blue.normal},
    TSPlaygroundFocus {},
    TSQueryLinterError {},
    TSPlaygroundLang {},
    TelescopeNormal {},
    TelescopeTitle {gui = "bold", fg = yellow.soft},
    TelescopePreviewLine {},
    TelescopePreviewMatch {},
    TelescopePreviewPipe {},
    TelescopePreviewCharDev {},
    TelescopePreviewDirectory {},
    TelescopePreviewBlock {},
    TelescopePreviewLink {},
    TelescopePreviewSocket {},
    TelescopePreviewRead {},
    TelescopePreviewWrite {},
    TelescopePreviewExecute {},
    TelescopePreviewHyphen {},
    TelescopePreviewSticky {},
    TelescopePreviewSize {},
    TelescopePreviewUser {},
    TelescopePreviewGroup {},
    TelescopePreviewDate {},
    TelescopePreviewMessage {},
    TelescopePreviewNormal {},
    TelescopePreviewMessageFillchar {},
    TelescopeResultsLineNr {},
    TelescopeResultsIdentifier {},
    TelescopeMultiSelection {},
    TelescopeMultiIcon {},
    TelescopeResultsDiffAdd {},
    TelescopeResultsBorder {},
    TelescopeResultsDiffDelete {},
    TelescopeResultsTitle {gui = "bold"},
    TelescopePromptNormal {},
    TelescopePromptBorder {},
    TelescopePromptTitle {gui = "bold"},
    TelescopePreviewBorder {},
    TelescopePreviewTitle {gui = "bold"},
    TelescopeResultsDiffUntracked {},
    TelescopeResultsClass {},
    TelescopePromptPrefix {},
    TelescopeResultsComment {},
    TelescopeResultsField {},
    TelescopeResultsDiffChange {},
    TelescopeResultsMethod {},
    TelescopeResultsSpecialComment {},
    TelescopeResultsOperator {},
    TelescopeResultsStruct {},
    TelescopeResultsNumber {},
    TelescopeResultsVariable {},
    TelescopeResultsFunction {},
    TelescopeResultsConstant {},
    TelescopeResultsNormal {},
    TelescopePromptCounter {fg = gray.normal},
    LspInfoList {},
    LspInfoTip {},
    LspInfoTitle {},
    LspInfoFiletype {},
    LspInfoBorder {},
    CmpItemAbbrDefault {fg = gray.light},
    CmpItemAbbrDeprecatedDefault {fg = gray.darker},
    CmpItemAbbrMatchDefault {fg = gray.light},
    CmpItemAbbrMatchFuzzyDefault {fg = gray.light},
    CmpItemKind {},
    CmpItemKindTypeParameterDefault {CmpItemKind},
    CmpItemKindSnippetDefault {CmpItemKind},
    CmpItemKindKeywordDefault {CmpItemKind},
    CmpItemKindStructDefault {CmpItemKind},
    CmpItemKindTextDefault {CmpItemKind},
    CmpItemKindConstructorDefault {CmpItemKind},
    CmpItemKindEventDefault {CmpItemKind},
    CmpItemKindClassDefault {CmpItemKind},
    CmpItemKindPropertyDefault {CmpItemKind},
    CmpItemKindConstantDefault {CmpItemKind},
    CmpItemKindFieldDefault {CmpItemKind},
    CmpItemKindEnumDefault {CmpItemKind},
    CmpItemKindFunctionDefault {CmpItemKind},
    CmpItemKindMethodDefault {CmpItemKind},
    CmpItemKindInterfaceDefault {CmpItemKind},
    CmpItemKindModuleDefault {CmpItemKind},
    CmpItemKindUnitDefault {CmpItemKind},
    CmpItemKindValueDefault {CmpItemKind},
    CmpItemKindVariableDefault {CmpItemKind},
    CmpItemKindColorDefault {CmpItemKind},
    CmpItemKindFileDefault {CmpItemKind},
    CmpItemKindReferenceDefault {CmpItemKind},
    CmpItemKindFolderDefault {CmpItemKind},
    CmpItemKindEnumMemberDefault {CmpItemKind},
    CmpItemKindOperatorDefault {CmpItemKind},
    CmpItemMenuDefault {fg = gray.light},
    CmpItemKindText {},
    CmpItemKindColor {},
    CmpItemKindFile {},
    CmpItemKindFolder {},
    GitSignsUntracked {},
    GitSignsUntrackedNr {},
    GitSignsChangedelete {},
    GitSignsChangedeleteNr {},
    GitSignsChangeNr {},
    GitSignsDeleteNr {},
    GitSignsTopdelete {},
    GitSignsTopdeleteNr {},
    GitSignsAddNr {},
    GitSignsAddLn {},
    GitSignsChangeLn {},
    GitSignsChangedeleteLn {},
    GitSignsUntrackedLn {},
    GitSignsStagedAdd {fg = green.dark},
    GitSignsStagedChange {fg = yellow.dark},
    GitSignsStagedDelete {fg = red.dark},
    GitSignsStagedChangedelete {fg = yellow.dark},
    GitSignsStagedTopdelete {fg = red.dark},
    GitSignsStagedAddNr {fg = green.dark},
    GitSignsStagedChangeNr {fg = yellow.dark},
    GitSignsStagedDeleteNr {fg = red.dark},
    GitSignsStagedChangedeleteNr {fg = yellow.dark},
    GitSignsStagedTopdeleteNr {fg = red.dark},
    GitSignsStagedAddLn {bg = green.dark},
    GitSignsStagedChangeLn {bg = blue.dark},
    GitSignsStagedChangedeleteLn {bg = blue.dark},
    GitSignsAddPreview {},
    GitSignsDeletePreview {},
    GitSignsCurrentLineBlame {},
    GitSignsAddInline {},
    GitSignsDeleteInline {},
    GitSignsChangeInline {},
    GitSignsAddLnInline {},
    GitSignsChangeLnInline {},
    GitSignsDeleteLnInline {},
    GitSignsDeleteVirtLn {},
    GitSignsDeleteVirtLnInLine {},
    GitSignsVirtLnum {},
    TodoBgHACK {gui = "bold", bg = yellow.soft, fg = gray.lighter},
    TodoFgHACK {fg = yellow.soft},
    TodoSignHACK {fg = yellow.soft},
    TodoBgTEST {gui = "bold", bg = yellow.soft, fg = gray.lighter},
    TodoFgTEST {fg = yellow.soft},
    TodoSignTEST {fg = yellow.soft},
    TodoBgTODO {gui = "bold", bg = blue.soft, fg = gray.lighter},
    TodoFgTODO {fg = blue.soft},
    TodoSignTODO {fg = blue.soft},
    TodoBgPERF {gui = "bold", bg = yellow.soft, fg = gray.lighter},
    TodoFgPERF {fg = yellow.soft},
    TodoSignPERF {fg = yellow.soft},
    TodoBgWARN {gui = "bold", bg = yellow.soft, fg = gray.lighter},
    TodoFgWARN {fg = yellow.soft},
    TodoSignWARN {fg = yellow.soft},
    TodoBgNOTE {gui = "bold", bg = green.soft, fg = gray.lighter},
    TodoFgNOTE {fg = green.soft},
    TodoSignNOTE {fg = green.soft},
    TodoBgFIX {gui = "bold", bg = red.soft, fg = gray.lighter},
    TodoFgFIX {fg = red.soft},
    TodoSignFIX {fg = red.soft},
    sym "@logcall" {bg = black, fg = yellow.soft},
  }
end)
